server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # This above is to have different names in case there are more than one instance

spring:
  application:
    name: animals-sender
  kafka:
    bootstrap-servers: ${kafka:localhost}:9092
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://${schema-registry:localhost}:8081

environment:
  animals-topic: animals