spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    # Don`t register it self
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      # default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
      default-zone: http://eureka-server:${server.port}/eureka/